# Change these first
owner: kabijamp # Your GitHub organization or username, where this repository lives
repo: upptimemonitor # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org

status-website:
  baseUrl: /upptimemonitor # where "repo" is your repository name
  name: Your Status Website
